/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app/projects/index'
import { Route as AuthenticatedAppProjectsProjectIdIndexRouteImport } from './routes/_authenticated/app/projects/$projectId/index'
import { Route as AuthenticatedAppProjectsProjectIdBoardsBoardIdRouteImport } from './routes/_authenticated/app/projects/$projectId/boards/$boardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/app/dashboard',
    path: '/app/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/app/projects/',
    path: '/app/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdIndexRoute =
  AuthenticatedAppProjectsProjectIdIndexRouteImport.update({
    id: '/app/projects/$projectId/',
    path: '/app/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdBoardsBoardIdRoute =
  AuthenticatedAppProjectsProjectIdBoardsBoardIdRouteImport.update({
    id: '/app/projects/$projectId/boards/$boardId',
    path: '/app/projects/$projectId/boards/$boardId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/app/projects/$projectId/': typeof AuthenticatedAppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/boards/$boardId': typeof AuthenticatedAppProjectsProjectIdBoardsBoardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/boards/$boardId': typeof AuthenticatedAppProjectsProjectIdBoardsBoardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/app/projects/$projectId/': typeof AuthenticatedAppProjectsProjectIdIndexRoute
  '/_authenticated/app/projects/$projectId/boards/$boardId': typeof AuthenticatedAppProjectsProjectIdBoardsBoardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/settings'
    | '/app/dashboard'
    | '/app/projects/'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/boards/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/settings'
    | '/app/dashboard'
    | '/app/projects'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/projects/'
    | '/_authenticated/app/projects/$projectId/'
    | '/_authenticated/app/projects/$projectId/boards/$boardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/app/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/projects/$projectId/': {
      id: '/_authenticated/app/projects/$projectId/'
      path: '/app/projects/$projectId'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/projects/$projectId/boards/$boardId': {
      id: '/_authenticated/app/projects/$projectId/boards/$boardId'
      path: '/app/projects/$projectId/boards/$boardId'
      fullPath: '/app/projects/$projectId/boards/$boardId'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdBoardsBoardIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
  AuthenticatedAppProjectsProjectIdIndexRoute: typeof AuthenticatedAppProjectsProjectIdIndexRoute
  AuthenticatedAppProjectsProjectIdBoardsBoardIdRoute: typeof AuthenticatedAppProjectsProjectIdBoardsBoardIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
  AuthenticatedAppProjectsProjectIdIndexRoute:
    AuthenticatedAppProjectsProjectIdIndexRoute,
  AuthenticatedAppProjectsProjectIdBoardsBoardIdRoute:
    AuthenticatedAppProjectsProjectIdBoardsBoardIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
