import { Link } from "@tanstack/react-router";
import { Menu, ShoppingBag, X, Search, Minus, Plus, Trash2, ArrowRight, PackageOpen, CircleAlert, LoaderCircle } from "lucide-react";
import { type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import { money, type Product, useStore } from "@/lib/store";

const nav = [{ label: "Home", to: "/" }, { label: "Products", to: "/products" }, { label: "Orders", to: "/orders" }, { label: "Profile", to: "/profile" }] as const;

export function Brand() { return <Link to="/" className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-primary text-xs font-bold text-primary-foreground">S</span><span className="font-display text-xl uppercase">ShopSphere</span></Link>; }
export function Navbar() {
  const { cartCount, user, signOut } = useStore();
  return <header className="sticky top-0 z-40 border-b border-border bg-background/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1320px] items-center gap-5 px-5"><Brand/><nav className="ml-2 hidden items-center gap-1 md:flex">{nav.map((item) => <Link key={item.to} to={item.to} className="rounded-lg px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-secondary hover:text-foreground" activeProps={{ className: "bg-secondary text-foreground" }}>{item.label}</Link>)}</nav><div className="ml-auto hidden items-center gap-2 sm:flex">{user ? <><span className="hidden text-sm font-semibold lg:block">Hi, {user.name.split(" ")[0]}</span>{user.role === "admin" && <Button asChild variant="ghost"><Link to="/admin">Admin</Link></Button>}<Button variant="ghost" onClick={signOut}>Logout</Button></> : <><Button asChild variant="ghost"><Link to="/login">Login</Link></Button><Button asChild><Link to="/register">Register</Link></Button></>}</div><Button asChild variant="outline" size="icon" className="relative"><Link to="/cart" aria-label={`Cart with ${cartCount} items`}><ShoppingBag/>{cartCount > 0 && <span className="absolute -right-2 -top-2 grid min-w-5 place-items-center rounded-full bg-primary px-1 text-[10px] font-bold text-primary-foreground">{cartCount}</span>}</Link></Button><Sheet><SheetTrigger asChild><Button variant="outline" size="icon" className="md:hidden"><Menu/><span className="sr-only">Open menu</span></Button></SheetTrigger><SheetContent className="bg-background p-6"><div className="mt-8 flex flex-col gap-2">{nav.map((item) => <Button key={item.to} asChild variant="ghost" className="justify-start"><Link to={item.to}>{item.label}</Link></Button>)}{user?.role === "admin" && <Button asChild variant="ghost" className="justify-start"><Link to="/admin">Admin</Link></Button>}<Button asChild variant="ghost" className="justify-start"><Link to={user ? "/profile" : "/login"}>{user ? user.name : "Login"}</Link></Button></div></SheetContent></Sheet></div></header>;
}
export function Footer() { return <footer className="mt-16 border-t border-border"><div className="mx-auto grid max-w-[1320px] gap-8 px-5 py-10 md:grid-cols-3"><div><Brand/><p className="mt-3 text-sm text-muted-foreground">Modern commerce. Simple shopping.</p></div><nav className="flex gap-8 text-sm font-semibold"><div className="flex flex-col gap-2"><Link to="/">Home</Link><Link to="/products">Products</Link></div><div className="flex flex-col gap-2"><Link to="/orders">Orders</Link><Link to="/profile">Profile</Link></div></nav><div className="text-sm text-muted-foreground md:text-right"><p className="font-bold uppercase text-foreground">Technology</p><p>React · Express · PostgreSQL</p></div></div></footer>; }
export function Layout({ children }: { children: ReactNode }) { return <><Navbar/><main className="mx-auto min-h-[70vh] max-w-[1320px] px-5">{children}</main><Footer/></>; }
export function PageHeader({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <div className="flex flex-col gap-4 py-10 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="font-display text-4xl uppercase sm:text-5xl">{title}</h1>{subtitle && <p className="mt-2 max-w-2xl text-muted-foreground">{subtitle}</p>}</div>{action}</div>; }
export function Stock({ stock }: { stock: number }) { return <span className={cn("text-xs font-bold", stock === 0 ? "text-muted-foreground" : stock <= 4 ? "text-primary" : "text-success")}>{stock === 0 ? "Out of Stock" : stock <= 4 ? `Only ${stock} left` : "In Stock"}</span>; }
export function ProductCard({ product }: { product: Product }) { const { addToCart } = useStore(); return <article className="group overflow-hidden rounded-2xl border border-border bg-card transition hover:-translate-y-1 hover:shadow-lg"><Link to="/products/$slug" params={{ slug: product.slug }} className="relative block overflow-hidden"><img src={product.imageUrl} alt={product.name} loading="lazy" width={1024} height={1024} className="aspect-square w-full object-cover transition duration-500 group-hover:scale-[1.03]"/><span className="absolute left-3 top-3 rounded-full bg-foreground px-2.5 py-1 text-[10px] font-bold uppercase text-background">{product.category}</span></Link><div className="p-4"><div className="flex items-start justify-between gap-3"><h2 className="font-bold">{product.name}</h2><span className="shrink-0 font-bold">{money(product.price)}</span></div><div className="mt-1"><Stock stock={product.stock}/></div><div className="mt-4 flex gap-2"><Button className="flex-1" disabled={!product.stock} onClick={() => addToCart(product)}>{product.stock ? "Add to Cart" : "Out of Stock"}</Button><Button asChild variant="outline"><Link to="/products/$slug" params={{ slug: product.slug }}>View Details</Link></Button></div></div></article>; }
export function SearchField({ value, onChange }: { value: string; onChange: (v: string) => void }) { return <div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={value} onChange={(e) => onChange(e.target.value)} placeholder="Search products..." className="h-11 pl-10"/></div>; }
export function Quantity({ value, max, onChange }: { value: number; max: number; onChange: (v: number) => void }) { return <div className="inline-flex h-10 items-center rounded-lg border border-border"><Button variant="ghost" size="icon" onClick={() => onChange(Math.max(1, value - 1))} aria-label="Decrease quantity"><Minus/></Button><span className="w-10 text-center text-sm font-bold">{value}</span><Button variant="ghost" size="icon" onClick={() => onChange(Math.min(max, value + 1))} disabled={value >= max} aria-label="Increase quantity"><Plus/></Button></div>; }
export function EmptyState({ title, message, action, to = "/products" }: { title: string; message: string; action: string; to?: "/products" | "/orders" }) { return <div className="rounded-2xl border border-dashed border-border py-16 text-center"><PackageOpen className="mx-auto size-10 text-primary"/><h2 className="mt-4 text-xl font-bold">{title}</h2><p className="mt-2 text-muted-foreground">{message}</p><Button asChild className="mt-6"><Link to={to}>{action}<ArrowRight/></Link></Button></div>; }
export function LoadingState() { return <div className="flex min-h-64 items-center justify-center"><LoaderCircle className="size-8 animate-spin text-primary"/><span className="sr-only">Loading</span></div>; }
export function ErrorState({ retry }: { retry?: () => void }) { return <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-10 text-center"><CircleAlert className="mx-auto size-9 text-destructive"/><h2 className="mt-3 text-xl font-bold">We couldn’t load this page</h2><p className="mt-2 text-muted-foreground">Please check your connection and try again.</p>{retry && <Button className="mt-5" onClick={retry}>Retry</Button>}</div>; }
export { Trash2, X };